
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about

# Social
social:
  email: abc@yah.csdf
  stack-overflow: st
  twitter: wtt
  facebook: trete
  linkedin: twert
  google: rewtert
  github: reterwte
  weibo: gtrwet
  douban: ertwe 
  zhihu: erwtewrt
  jianshu:  rewterwt
  pocket: retrewt
  tumblr: terwtrwet
  instagram: erwtetwe

# Miscelaneous
favicon: /favicon.ico
logo: /logo.png
logo_dark: /logo_dark.png

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/simple.js

# Site creation time
since: 2017

# Blog auto_excerpt
auto_excerpt:
  enable: true
  length: 150
