
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about

# Social
social:
  email: 
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: 
  weibo:
  douban:
  zhihu:
  jianshu: 
  pocket:
  tumblr:
  instagram:

# Miscelaneous
favicon: /favicon.ico
logo: /logo.png

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/simple.js

# Site creation time
since: 2017

# Blog auto_excerpt
auto_excerpt:
  enable: true
  length: 150
